spring.application.name=preppilot

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/preppilot_db
spring.datasource.username=root
spring.datasource.password=Whyme?123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=your-super-secret-key-minimum-32-chars-long-replace-this
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000

# Mail (fill later on Day 5)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youremail@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true